name: Generate Profile Assets

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/tron-dark-snake.svg?palette=github-dark&color_snake=#00BFFF&color_dots=#152238,#1e3860,#274e8a,#3164b3,#00BFFF
            dist/tron-light-snake.svg?palette=github&color_snake=#00BFFF&color_dots=#152238,#1e3860,#274e8a,#3164b3,#00BFFF
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-3d-contrib:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: "settings.json"
      - name: Commit & Push
        run: |
          mkdir -p assets # Ensure the assets folder exists
          mv profile-3d-contrib/profile-customize.svg assets/ # Move the file
          rm -rf profile-3d-contrib # Remove the old folder
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
